import { NextAuthProvider } from "@/lib/provider";
import FooterComponent from "./components/Footer/Footer";
import "./globals.css";
// import { Righteous } from "next/font/google";
import { Barlow } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Movie app using Next.js",
  description: "Generated by create next app",
};

const barlow = Barlow({
  subsets: ["latin"],
  font: "google",
  weight: "400",
  style: "normal",
});
// const righteous = Righteous({
//   subsets: ["latin"],
//   font: "google",
//   weight: "400",
//   style: "normal",
// });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"min-h-screen " + barlow.className}>
        <NextAuthProvider>
          <header className="sticky top-0 z-50 text-3xl sm:text-md md:text-xl lg:text-lg xl:text-xl lg:justify-self-start">
            <Navbar />
          </header>
          {children}
          <FooterComponent />
        </NextAuthProvider>
      </body>
    </html>
  );
}
